// <auto-generated />
using System;
using DiplomTsvetkova;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiplomTsvetkova.Migrations
{
    [DbContext(typeof(DiplomTsvetkovaContext))]
    [Migration("20220606191736_Number666")]
    partial class Number666
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DiplomTsvetkova.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("DiplomTsvetkova.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductStorageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quatity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProductStorageId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DiplomTsvetkova.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e81"),
                            Image = "1.jpg",
                            Name = "BANAN1",
                            Price = 1m
                        },
                        new
                        {
                            Id = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e82"),
                            Image = "1.jpg",
                            Name = "BANAN2",
                            Price = 12m
                        },
                        new
                        {
                            Id = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e83"),
                            Image = "1.jpg",
                            Name = "BANAN3",
                            Price = 123m
                        },
                        new
                        {
                            Id = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e84"),
                            Image = "1.jpg",
                            Name = "BANAN4",
                            Price = 1234m
                        },
                        new
                        {
                            Id = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e85"),
                            Image = "1.jpg",
                            Name = "BANAN5",
                            Price = 12345m
                        });
                });

            modelBuilder.Entity("DiplomTsvetkova.Models.ProductStorage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("StorageId");

                    b.ToTable("ProductStorages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f03243da-5609-4beb-98aa-730c1d4f66e4"),
                            ProductId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e81"),
                            Quantity = 100,
                            StorageId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e11")
                        },
                        new
                        {
                            Id = new Guid("a87ee831-7d8b-476f-b1e8-2da57ff05fba"),
                            ProductId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e82"),
                            Quantity = 100,
                            StorageId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e13")
                        },
                        new
                        {
                            Id = new Guid("bc35d3c5-42b3-498e-83a5-79c900e575c7"),
                            ProductId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e82"),
                            Quantity = 100,
                            StorageId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e12")
                        },
                        new
                        {
                            Id = new Guid("c5745ae3-58fd-4aeb-813c-3883a740b6d0"),
                            ProductId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e83"),
                            Quantity = 100,
                            StorageId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e12")
                        },
                        new
                        {
                            Id = new Guid("256b0c54-73aa-4c8d-80af-6ec378e66bf9"),
                            ProductId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e84"),
                            Quantity = 100,
                            StorageId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e13")
                        },
                        new
                        {
                            Id = new Guid("ab9031f3-8a4d-45c5-ad94-313e21b8606b"),
                            ProductId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e81"),
                            Quantity = 100,
                            StorageId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e13")
                        },
                        new
                        {
                            Id = new Guid("2e174abb-b309-48c7-9164-0887fdc21ee3"),
                            ProductId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e85"),
                            Quantity = 100,
                            StorageId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e12")
                        },
                        new
                        {
                            Id = new Guid("0cd515d3-a863-40d0-97dc-50fe419d6384"),
                            ProductId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e85"),
                            Quantity = 100,
                            StorageId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e11")
                        },
                        new
                        {
                            Id = new Guid("269dd2ac-fdb6-4482-8231-73b01c219b1c"),
                            ProductId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e81"),
                            Quantity = 100,
                            StorageId = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e12")
                        });
                });

            modelBuilder.Entity("DiplomTsvetkova.Models.Storage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Storages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e11"),
                            Address = "Ново-Московская ул., 2/8, Смоленск, Смоленская обл., 214000",
                            Latitude = 54.795332076323433,
                            Longitude = 32.055647589620733,
                            Name = "BANANOSKLAD1"
                        },
                        new
                        {
                            Id = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e12"),
                            Address = "ул. 25 Сентября, 35А, Смоленск, Смоленская обл., 214031",
                            Latitude = 54.770775521219925,
                            Longitude = 32.079753946338514,
                            Name = "BANANOSKLAD2"
                        },
                        new
                        {
                            Id = new Guid("774ae5ac-ca59-49f2-8c07-c36dd7826e13"),
                            Address = "ул. Нормандии-Неман, 35, Смоленск, Смоленская обл., 214025",
                            Latitude = 54.780128699072407,
                            Longitude = 32.016695035303151,
                            Name = "BANANOSKLAD3"
                        });
                });

            modelBuilder.Entity("DiplomTsvetkova.Models.Order", b =>
                {
                    b.HasOne("DiplomTsvetkova.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomTsvetkova.Models.ProductStorage", "ProductStorage")
                        .WithMany("Orders")
                        .HasForeignKey("ProductStorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ProductStorage");
                });

            modelBuilder.Entity("DiplomTsvetkova.Models.ProductStorage", b =>
                {
                    b.HasOne("DiplomTsvetkova.Models.Product", "Product")
                        .WithMany("ProductStorages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomTsvetkova.Models.Storage", "Storage")
                        .WithMany("ProductStorages")
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("DiplomTsvetkova.Models.Product", b =>
                {
                    b.Navigation("ProductStorages");
                });

            modelBuilder.Entity("DiplomTsvetkova.Models.ProductStorage", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DiplomTsvetkova.Models.Storage", b =>
                {
                    b.Navigation("ProductStorages");
                });
#pragma warning restore 612, 618
        }
    }
}
